indent = 4
margin = 92
pipe_to_function_call = true
whitespace_typedefs = true
whitespace_in_kwargs = false
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_for_in = true
conditional_to_if = true
separate_kwargs_with_semicolon = true
